[project]
name = "echoesphere-agent"
version = "0.1.0"
description = "EchoSphere Agent"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ddgs>=9.11.4",
    "pillow>=12.1.1",
    "python-dotenv>=1.2.2",
    "smolagents[litellm]>=1.24.0",
]

[project.optional-dependencies]
dev = ["jupyter"]